name: build

on:
  push:
    tags:
      - "v*"

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install -y libxtst-dev
      - name: Build
        uses: crazy-max/ghaction-xgo@v3.0.0
        with:
          xgo_version: latest
          go_version: 1.22
          dest: dist
          prefix: mv_cursor
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/arm64
          v: true
          x: true
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          buildvcs: true
      - uses: echapmanFromBunnings/upload-artifact@3.0
        with:
          name: "releases"
          path: "dist/**/*"
          if-no-files-found: "warn" # Optional
          retention-days: 10 # Optional
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "dist/**/*"
          body: "Yet another release"
          makeLatest: true
